### ISSUE TITLE
Error Fetching hostname on OS X

### ISSUE THREAD

**Issue by snoe** [weaver/node-mail#1]
Hi, trying to use the library on OS X, I receive this stack trace when sending:

Error: Process exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/mail/0.1.0/package/lib/mail/util.js:296:16)
    at ChildProcess.emit (events:33:26)
    at ChildProcess.onexit (child_process:151:12)
    at node.js:769:9

Seems the -f option doesn't exist on os x...
$ hostname -f
hostname: illegal option -- f
usage: hostname [-s] [name-of-host]

**Comment by weepy** [comment]
i think it's a problem with Leopard

**Comment by weaver** [comment]
Hi snoe, sorry for the late reply.  Try pulling the latest master branch or updating to 0.1.1 in npm.  This update contains weepy's patch that fixes a race condition around the `domain` setting.  

Use the `domain` setting as a workaround.  `node-mail` only uses `hostname` if `domain` isn't already set.  I'll try to make a better solution in the long-term.  Let me know if you're still having trouble.

```
var mail = require('../lib/mail').Mail({
  domain: 'my.local.hostname',
  // more settings here...
});
```

**Comment by weaver** [comment]
I just pushed an updated to make node-mail work with Node 0.4.x. Part of Node's new API is an `os.hostname()` method, so this should be resolved. Thanks!
