### ISSUE TITLE
doesn't work with node >= 0.4

### ISSUE THREAD

**Issue by coolaj86** [weaver/node-mail#12]
This snippet is supposed to provide some insight on the 0.2 -> 0.4 migration of net.Stream. I don't have the time right now to look over your code closely enough to apply it.

https://gist.github.com/848444

Is this something you're likely to fix soon (days or weeks)?

**Comment by weaver** [comment]
I'm migrating the project I made this for originally to Node 0.4, so it'll probably be this week.

**Comment by weaver** [comment]
It should work just fine with Node 0.4.x now.
