### ISSUE TITLE
Update your docs

### ISSUE THREAD

**Issue by indexzero** [weaver/node-mail#13]
Docs say:

"Node Mail has been tested against qmail and gmail using Node version v0.1.103. A working subset of these RFCs are supported:"

package.json says:
`"engines": { "node": ">= 0.4.0 < 0.5.0" }`

**Comment by weaver** [comment]
Thanks for the bug report. It looks like you caught me just before I pushed the README update :)

**Comment by indexzero** [comment]
Haha. My pleasure _bow_
