### ISSUE TITLE
base64

### ISSUE THREAD

**Issue by dvv** [weaver/node-mail#5]
Hi!

Please, consider using `(str||'').toString()` in L#18 of base64.js

--Vladimir

**Comment by thisismedium** [comment]
Hi Vladimir.  I'm happy to change this.  Could you tell me if you ran into a problem using node-mail?  I'd like to investigate in case there's a logic error somewhere else in the code.

Thanks!

**Comment by dvv** [comment]
Yep. I've a SMTP server which doesn't _require_ authentication but node-mail still issued authLOGIN w/o settings.username set. That's how I came to the issue. A quick hack was to silence the exception by not allowing undefined propagate to base64(). But, of course, the prob persists -- node-mail tries quite aggressively authenticate to the server even if auth is not required. Wonder if it could be fixed? May be a settings.auth method switcher or such?

TIA,
--Vladimir

**Comment by weaver** [comment]
Thanks, Vladimir.  Authentication should only be attempted when a username is set. I must have refactored that away at some point :)  It should be fixed now.  Try pulling the latest patches or update to 0.1.1 if you're using npm.  

Let me know if you're still having trouble!

Many thanks,

-Ben

**Comment by dvv** [comment]
Works. Thanks!

Your client seems the only which ever analyzes the _answers_ from SMTP server, not sending a stream of commands as into a black hole. Very cool! (Just FYI, I maintain sendmail (and other mailing stuff) in BusyBox project (http://git.busybox.net/busybox/tree/mailutils/sendmail.c), so I can speak how difficult is to decide on that)

Another little sugars to usability could be:
- derive settings.domain from the sender address
- allow for external credentials (like an external 0600 mode file)

Best regards,
--Vladimir

**Comment by dvv** [comment]
Oh, and another feature would be very welcome -- an optionally allowed (via settings.debug?) dumping of sent/received stuff

TIA,
--Vladimir

**Comment by weaver** [comment]
Thanks for the ideas.  The debug setting and external credentials sound useful. I'll add them soon.

Deriving settings.domain from the sender address sounds interesting. Do you know if there are other mail clients that do this? I'm a little concerned that it blurs the boundary between a client session and a mail transaction.

Thanks,

-Ben

**Comment by dvv** [comment]
I believe standard `sendmail` requires only a sender address to start talking to the server. Even more, if `sendmail` is given `-t` option, it reads sender address from the message headers fed via stdin. The servers expect to see the domain name of the _mail server_ in ehlo/helo, not client `hostname`, so cutting off sender address is a good shot. Plus, it can be overwritten by explicit settings.domain, which makes the config very flexible

--Vladimir

**Comment by weaver** [comment]
Thanks, I'll look into it.  

FWIW, my reading of RFC 5321 is that clients should identify themselves with their own hostname when sending `EHLO` (e.g. [Typical Scenario](http://tools.ietf.org/html/rfc5321#appendix-D.1)).  I just checked Python's `smtplib` and it uses `getfqdn` / `gethostname` if the domain isn't passed to the constructor.

The extra sugar would definitely feel simpler; I'll look at some other clients to see how they handle this problem.

I really appreciate the feedback and suggestions.

-Ben
