### ISSUE TITLE
Error for body has non-ascii charecters.

### ISSUE THREAD

**Issue by katoy** [weaver/node-mail#7]
Tring sending Japanese mail, I got the error "Data must be 7-bit ASCII.'
It causes in ClientTransaction.prototype.write = function(data).
Comment-outed the checking 7bit, I can send the mail.

Do you have better ways for non-ascii char in body?
// Also I need the solution for non-ascii in subject.

**Comment by weaver** [comment]
Hi katoy,

That error is there to remind me to implement proper MIME support sometime. Based on [8BITMIME](http://cr.yp.to/smtp/8bitmime.html) it seems fine to comment out that line as a workaround. I'll keep this ticket open until there's a proper fix.

Thanks!

**Comment by weaver** [comment]
Hey katoy,

I pushed an update for `node-mail` today so it works with Node 0.4.x. I've also added support for RFC-6152 (8-bit mime transport) which should solve this problem.

Thanks!

**Comment by katoy** [comment]
Thank, it works fine.
